version: '3.9'

services:
  web:
    build: .
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"

volumes:
  postgres_data:
